build:
    stage: build
    script:
        - cmake -DPIMORONI_INKY_BUILD_TESTS=1 -DPIMORONI_INKY_BUILD_INST_CODE=1 -S . -B build
        - cmake --build build
    artifacts:
        paths:
            - build
        expire_in: 1 day
test:
    stage: test
    script:
        - cd build
        - make inky-fb-test-coverage
    artifacts:
        paths:
            - build/coverage.json
        expire_in: 1 day
    coverage: '/Coverage: \d+\.\d+/'